######################################################################## 
# $Id:: makefile 6042 2010-12-23 10:29:32Z ing02124                    $
# 
# Project: Example makefile
#
# Notes:
#     This makefile generates an image that will load in SRAM at
#     address 0x11029000. The image can be loaded and run with the
#     UART.
#
# Description: 
#  Makefile
# 
######################################################################## 
# Software that is described herein is for illustrative purposes only  
# which provides customers with programming information regarding the  
# products. This software is supplied "AS IS" without any warranties.  
# NXP Semiconductors assumes no responsibility or liability for the 
# use of the software, conveys no license or title under any patent, 
# copyright, or mask work right to the product. NXP Semiconductors 
# reserves the right to make changes in the software without 
# notification. NXP Semiconductors also make no representation or 
# warranty that such application will be suitable for the specified 
# use without further testing or modification. 
########################################################################

EXECNAME    = rtc_demo
include $(NXPMCU_SOFTWARE)/csps/$(CSP)/bsps/$(BSP)/examples/common/makefile.ex





