/*
 * Automatically generated C config: don't edit
 * Linux kernel version: KERNELVERSION
 * Sat Mar  1 11:00:04 2014
 */
#define AUTOCONF_INCLUDED
#define CONFIG_ALIASES 1
#define CONFIG_ALLHELP 1
#define CONFIG_CMD_SETENV 1
#define CONFIG_ENV_REGION "lnand:512k+256k"
#define CONFIG_STACK_SIZE 0x1000
#define CONFIG_USES_PATHNAME_PARSER 1
#define CONFIG_MACH "lpc313x"
#define CONFIG_CMD_ENV 1
#define CONFIG_CPU_ARM926T 1
#define CONFIG_ATAG 1
#define CONFIG_SPINNER 1
#define CONFIG_CMD_IMAGE_APEX 1
#define CONFIG_DYNAMIC_CLOCKS 1
#define CONFIG_ENV_REGION_KERNEL "lnand:768k+2m"
#define CONFIG_ENV_SAVEATONCE 1
#define CONFIG_CMD_IMAGE_SHOW 1
#define CONFIG_CC_OPTIMIZE_FOR_SIZE 1
#define CONFIG_CMD_COMPARE 1
#define CONFIG_ARCH_NUMBER 9998
#define CONFIG_CMD_DRVINFO 1
#define CONFIG_ARCH_LPC313X 1
#define CONFIG_DRIVER_EXT2 1
#define CONFIG_ENV_MUTABLE 1
#define CONFIG_AEABI 1
#define CONFIG_CMD_FILL 1
#define CONFIG_USES_SSD1963 1
#define CONFIG_CMD_INFO 1
#define CONFIG_CPU_ARM9 1
#define CONFIG_COMMAND_EDITING 1
#define CONFIG_ENV_DEFAULT_CMDLINE_OVERRIDE 1
#define CONFIG_CMD_WAIT 1
#define CONFIG_CMD_DUMP 1
#define CONFIG_TARGET_DESCRIPTION "Embedded Projects EPLPC3131"
#define CONFIG_CMD_COPY 1
#define CONFIG_PARTIAL_MATCHES 1
#define CONFIG_APEX_VMA 0x11029000
#define CONFIG_USES_LCD 1
#define CONFIG_OSC_FREQ 12000000
#define CONFIG_RELOCATE_SIMPLE 1
#define CONFIG_ENV_SIZE 16384
#define CONFIG_CMD_CHECKSUM 1
#define CONFIG_CMD_XRECEIVE 1
#define CONFIG_COMMAND_HISTORY 1
#define CONFIG_CMD_IMAGE 1
#define CONFIG_MACH_EPLPC3131_V1 1
#define CONFIG_CMD_ALIAS 1
#define CONFIG_ENV_DEFAULT_STARTUP_OVERRIDE 1
#define CONFIG_CMD_ERASE 1
#define CONFIG_ENV_DEFAULT_CMDLINE "console=ttyS0,115200n8 console=tty0 root=/dev/mmcblk0p3 rw rootwait"
#define CONFIG_CPU_ARMV5 1
#define CONFIG_NO_BOOTSTRAP 1
#define CONFIG_ATAG_PHYS 0x30000100
#define CONFIG_DEL_IS_BS 1
#define CONFIG_ANSI_KEYS 1
#define CONFIG_DRIVER_EXT2_BLOCKDEVICE "mmc"
#define CONFIG_CMD_GO 1
#define CONFIG_DISABLE_MMU_AT_BOOT 1
#define CONFIG_RAM_SIZE_32MB 1
#define CONFIG_ALPHABETIZE_COMMANDS 1
#define CONFIG_ENV_DEFAULT_STARTUP "wait 2; copy ext2://1/zImage 0x30008000; boot"
#define CONFIG_PLL_180 1
#define CONFIG_ARM 1
#define CONFIG_ENV_CHECK_LEN 1024
#define CONFIG_SDRAMBOOT_REPORT 1
#define CONFIG_ENV 1
#define CONFIG_CROSS_COMPILE "arm-linux-gnueabi-"
#define CONFIG_KERNEL_LMA 0x30008000
