CONFIG_CMD_FAT=y
CONFIG_USB_DFU=y
CONFIG_CMD_ITEST=y
CONFIG_CMD_EDITENV=y
CONFIG_SYS_GBL_DATA_SIZE=128
CONFIG_SYS_LONGHELP=y
CONFIG_CPU_USBDFU_BOOT=y
CONFIG_SYS_LOAD_ADDR=11029000
CONFIG_CMD_XIMG=y
CONFIG_STACKSIZE="0x1000"
CONFIG_BOOTDELAY=5
CONFIG_SPI_FLASH=y
CONFIG_SYS_HELP_CMD_WIDTH=8
CONFIG_NR_DRAM_BANKS=y
CONFIG_SYS_CBSIZE=256
CONFIG_USBD_DFU_INTERFACE=2
CONFIG_CMD_CONSOLE=y
CONFIG_USBD_PRODUCT_NAME=""LPC313x Bootloader " U_BOOT_VERSION"
CONFIG_MMC=y
CONFIG_CMD_MISC=y
CONFIG_USB_EHCI_LPC313X=y
CONFIG_MISC_INIT_R=y
CONFIG_ENV_OFFSET="0x00"
CONFIG_RELOC_FIXUP_WORKS=y
CONFIG_ENV_OVERWRITE=y
CONFIG_CMD_NET=y
CONFIG_CMD_NFS=y
CONFIG_ENV_SIZE="0x800"
CONFIG_SYS_MALLOC_LEN="(1 * 1024 * 1024)"
CONFIG_LPC313X=y
CONFIG_INITRD_TAG=y
CONFIG_CMD_FLASH=y
CONFIG_ARM_THUMB=y
CONFIG_CMD_SAVEENV=y
CONFIG_USB_DEVICE=y
CONFIG_CMD_MEMORY=y
CONFIG_SYS_MAXARGS=16
CONFIG_CMD_RUN=y
CONFIG_SYS_PBSIZE="(CONFIG_SYS_CBSIZE+sizeof(CONFIG_SYS_PROMPT)+16)"
CONFIG_SUPPORT_VFAT=y
CONFIG_CMDLINE_EDITING=y
CONFIG_CMD_USB=y
CONFIG_USB_EHCI=y
CONFIG_BOOTCOMMAND="run sd_boot"
CONFIG_ISO_PARTITION=y
CONFIG_USB_TTY=y
CONFIG_CMD_SETGETDCR=y
CONFIG_CMD_BOOTD=y
CONFIG_USBD_PRODUCTID_CDCACM="0x5119"
CONFIG_SYS_BARGSIZE="CONFIG_SYS_CBSIZE"
CONFIG_AUTO_COMPLETE=y
CONFIG_SYS_HZ="(XTAL_IN / 256)"
CONFIG_DOS_PARTITION=y
CONFIG_CMD_FPGA=y
CONFIG_SYS_BAUDRATE_TABLE="{ 9600, 19200, 38400, 57600, 115200 }"
CONFIG_USBD_DFU_XFER_SIZE=4096
CONFIG_CMD_ECHO=y
CONFIG_USBD_VENDORID="0x1457"
CONFIG_LPC313X_SPI=y
CONFIG_EXTRA_ENV_SETTINGS="loadaddr=0x31000000\0rd_addr=0x32000000\0addrx=0x30100000\0usbtty=cdc_acm\0myargs=setenv bootargs console=ttyS0,115200n8 root=/dev/mmcblk0p3 ro rootwait\0serverip=192.168.1.48\0nfsargs=setenv bootargs console=ttyS0,115200n8 root=/dev/nfs rw nfsroot=${serverip}:${rootpath} ip=dhcp loglevel=7\0rootpath=/tftpboot/arm\0bootfile=uImage\0ramfile=rootfs.ext2.gz.uboot\0net_boot=dhcp; run nfsargs; bootm $(loadaddr)\0spi_boot= sf probe 0 0 0; sf read $(loadaddr) 0x42000 0x200000; run nfsargs; bootm $(loadaddr)\0nand_boot= nand read $(loadaddr) 0x80000 0x200000; run nfsargs; bootm $(loadaddr)\0sdmmc_boot= mmc init; fatload mmc 0 $(loadaddr) $(bootfile); run nfsargs; bootm $(loadaddr)\0usbdfu_boot= usbpoll $(loadaddr); run nfsargs; bootm $(loadaddr)\0usb_boot= usb start; fatload usb 0 $(loadaddr) $(bootfile); run nfsargs; bootm $(loadaddr)\0uart_boot= loady; run nfsargs; bootm $(loadaddr)\0netram_boot=dhcp; tftp $(rd_addr) $(ramfile); run ramargs; bootm $(loadaddr) $(rd_addr)\0spiram_boot= sf probe 0 0 0; sf read $(loadaddr) 0x42000 0x200000; sf read $(rd_addr) 0x243000 0x400000; run ramargs; bootm $(loadaddr) $(rd_addr)\0nandram_boot= nand read $(loadaddr) 0x80000 0x200000; nand read $(rd_addr) 0x2a0000 0x400000; run ramargs; bootm $(loadaddr) $(rd_addr)\0sdmmcram_boot= mmc init; fatload mmc 0 $(loadaddr) $(bootfile); fatload mmc 0 $(rd_addr) $(ramfile); run ramargs; bootm $(loadaddr) $(rd_addr)\0usbdfuram_boot= usbpoll $(loadaddr); usbpoll $(rd_addr); run ramargs; bootm $(loadaddr) $(rd_addr)\0usbram_boot= usb start; fatload usb 0 $(loadaddr) $(bootfile); fatload usb 0 $(rd_addr) $(ramfile); run ramargs; bootm $(loadaddr) $(rd_addr)\0uartram_boot= loady; loady $(rd_addr); run ramargs; bootm $(loadaddr) $(rd_addr)\0sd_boot= mmc init; fatload mmc 0 $(addrx) $(bootfile); run myargs; bootm $(addrx)\0"
CONFIG_BOOTFILE="uImage"
CONFIG_BAUDRATE=115200
CONFIG_CMD_AUTOSCRIPT=y
CONFIG_CMDLINE_TAG=y
CONFIG_ENV_IS_NOWHERE=y
CONFIG_SYS_DEF_EEPROM_ADDR=0
CONFIG_CPU_MMC_BOOT=y
CONFIG_USBD_MANUFACTURER="OpenMoko, Inc"
CONFIG_SYS_MEMTEST_END="0x31ffffff"
CONFIG_SYS_NO_FLASH=y
CONFIG_EA3131=y
CONFIG_CMD_SOURCE=y
CONFIG_SYS_PROMPT="GNUBLIN # "
CONFIG_USB_STORAGE=y
CONFIG_SETUP_MEMORY_TAGS=y
CONFIG_SERIAL1=y
CONFIG_SYS_MEMTEST_START="0x30000000"
CONFIG_CMD_LOADB=y
CONFIG_CMD_LOADS=y
CONFIG_CMD_IMI=y
CONFIG_HARD_SPI=y
CONFIG_ARM=y
CONFIG_CMD_BDI=y
CONFIG_EHCI_IS_TDI=y
CONFIG_CMD_MMC=y
