.TH FLASH-APEX 8
.SH NAME
flash-apex \- write APEX binary image into MTD flash
.SH SYNOPSIS
.B flash-apex
.SH DESCRIPTION

The \fBflash-apex\fR script reads a raw (objdump'd) APEX binary image
from the file \fI/boot/apex.flash\fR, also part of the apex-nslu2 package,
and writes it into MTD flash.  It is called automatically from the
package postinst script.

\fBflash-apex\fR is designed to safely upgrade APEX.  It executes
properly on either big or little endian machiness, compensating for
endianness mismatch as necessary.  Before flashing, it reads the APEX
configuration environment from MTD flash using apex-env(8) and then
writes it back into MTD after writing the APEX image.  In this
release, \fBflash-apex\fR only supports the Linksys NSLU2.

If you need to flash a custom version of APEX, move the file
\fI/boot/apex.flash\fR out of the way, write your image to
\fI/boot/apex.flash\fR, and run \fBflash-apex\fR.

\fBflash-apex\fR requires the \fI/dev/mtd\fR driver.

.SH WARNING
Though this script has been thoroughly tested, it modifies boot-flash.
A failure during this process could prevent your NSLU2 from booting.
In this event, you'll need to use upgrade mode to restore the NSLU2 to
a working state.  Use \fI/boot/apex.flash\fR to install a custom
version of APEX only if you know what you are doing and only when you
have a backup of MTD flash.

.SH OPTIONS
none

.SH FILES

.TP
/boot/apex.flash
The APEX binary image written to MTD flash by \fBflash-apex\fR.

.SH BUGS
Please check the debian bug tracking system at http://bugs.debian.org/src:apex
for known bugs before reporting any new bugs there.

.SH AUTHOR
\fBflash-apex\fR was written by Gordon Farquharson
<gordonfarquharson@gmail.com>, Martin Michlmayr <tbm@cyrius.com>, and Joey
Hess <joeyh@debian.org>. This manpage was written by Kevin Price
<kp@kevin-price.de> and Marc Singer <elf@debian.org>.

.SH SEE ALSO
http://www.nslu2-linux.org/wiki/Info/BootFlash

.SH COPYING

The script and this manpage are copyrighted and protected by the GNU GPL.
