//tealium universal tag - utag.10 ut4.0.201409121556, Copyright 2014 Tealium.com Inc. All Rights Reserved.
window.GoogleAnalyticsObject="";if(window.GoogleAnalyticsObject==""){window.GoogleAnalyticsObject="ga"};window[window.GoogleAnalyticsObject]=window[window.GoogleAnalyticsObject]||function(){(window[window.GoogleAnalyticsObject].q=window[window.GoogleAnalyticsObject].q||[]).push(arguments);};var wap_ga={};wap_ga.tms={};wap_ga.qs={};wap_ga.config={};wap_ga.campaign={};wap_ga.ulit={};try{(function(id,loader,u){try{u=utag.o[loader].sender[id]={}}catch(e){u=utag.sender[id]};u.ev={'view':1,'link':1};u.o=window[window.GoogleAnalyticsObject];u.cookieDomain=""||utag.loader.lh();u.created=false;u.name="wap";window.ga_trackerName="wap";u.account="UA-35949610-4,UA-15153107-1";window.ga_account="UA-35949610-4,UA-15153107-1";u.anonymizeIp=("true"==="true"?true:false);window.ga_anonymizeip=("true"==="true"?true:false);u.allowLinker=false;u.crossDomainTrack="";wap_ga.tms.enhancedLinkAttribution="true";u.displayfeatures="true";u.map={"wa_geo":"dimension1","wa_local":"dimension2","wa_section":"dimension3","wa_visit_id":"dimension100","wa_site_id":"dimension4","wa_site_id_audience":"dimension5","wa_org2":"dimension6","wa_page_type_micro":"dimension13","wa_page_type_macro":"dimension14","wa_login":"dimension15","wa_english_title":"dimension16","wa_target_audience":"dimension17","wa_resource_type":"dimension18","content_org_initiative":"dimension20","content_product":"dimension22","wa_product_id":"dimension24","wa_personalization_segment":"dimension26","wa_campaign":"dimension30","wa_metrics_campaign":"dimension31","wa_intel_technology":"dimension32","wa_metrics_segment":"dimension33","wa_system_type":"dimension34","wa_program_level":"dimension35","wa_sales_life_cycle":"dimension36","wa_topic":"dimension37","wa_applications":"dimension38","wa_intel_platform":"dimension39","wa_internal_search_referrer":"dimension42","wa_zero_search_results":"dimension43","content_audience":"dimension58","content_program":"dimension62","content_sub_audience":"dimension63","wa_profile_id":"dimension102","wa_business_id":"dimension103","wa_program_id":"dimension104","wa_elq_id":"dimension105","wa_sprinklr_id":"dimension108","wa_org3":"dimension7","wa_org4":"dimension8","wa_org5":"dimension9","wa_org6":"dimension10","wa_org7":"dimension11","wa_org8":"dimension12","wa_do_not_track":"dimension59","wa_campaign_cid":"dimension107","wa_user_task":"dimension65","wa_product_name":"dimension23","wa_external_id":"dimension109","wa_rwd":"dimension60","wa_error":"dimension66","wa_transl_status":"dimension73","wa_author":"dimension74"};u.extend=[];u.send=function(a,b){if(u.ev[a]||typeof u.ev.all!="undefined"){var c,d,e,f,g;for(d in utag.loader.GV(u.map)){if(typeof b[d]!="undefined"&&b[d]!=""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u[e[f]]=b[d];wap_ga.tms[e]=b[d];}}}
}}
try{utag.o[loader].loader.LOAD(id)}catch(e){utag.loader.LOAD(id)}})('10','intel.profile-communities');}catch(e){}
wap_ga.doc=document;wap_ga.win=window;wap_ga.undef=undefined;wap_ga.noset='unassigned';wap_ga.code='tms.1.0';wap_ga.env=(typeof wa_env!=="undefined")?wa_env:true;wap_ga.scroll=(typeof waTrackScroll!=="undefined")?waTrackScroll:true;wap_ga.wa_local=(typeof utag_data.wa_local!=="undefined")?utag_data.wa_local:wap_ga.noset;wap_ga.section=(typeof utag_data.wa_section!=="undefined")?utag_data.wa_section:wap_ga.noset;wap_ga.autofire=(typeof ga_auto_fire!=="undefined")?ga_auto_fire:true;wap_ga.pagename=(typeof ga_page_name!=="undefined")?ga_page_name:'';wap_ga.callback=(typeof ga_callback!=="undefined")?ga_callback:wap_ga.undef;wap_ga.pagegroup=(typeof ga_page_group!=="undefined")?ga_page_group:location.pathname;wap_ga.sitespeed=(wap_ga.win.ga_setSampleRate)?wap_ga.win.ga_setSampleRate:100;wap_ga.name=(typeof ga_trackerName!=="undefined")?"gawap":"gawap";wap_ga.qs.cid=tmsGetParamByName('cid');wap_ga.qs.eid=tmsGetParamByName('eid');wap_ga.qs.dfaid=tmsGetParamByName('dfaid');wap_ga.qs.dclid=tmsGetParamByName('dclid');wap_ga.qs.gclid=tmsGetParamByName('gclid');wap_ga.qs.utm=tmsGetParamByName('utm_campaign');wap_ga.qs.wapkw=tmsGetParamByName('wapkw');wap_ga.campaign=(wap_ga.qs.cid||wap_ga.qs.eid)?true:false;wap_ga.config.campaign=function(){if(wap_ga.qs.utm){wap_ga.campaign=false;}
if(wap_ga.qs.dclid){wap_ga.campaign=false;}
if(wap_ga.qs.gclid){wap_ga.campaign=false;}
if(wap_ga.qs.cid){ga_payload.dimension['107,page']=wap_ga.qs.cid;}
var errorType='campaign.other',error='',errorVal='',errorwapkw=(wap_ga.qs.wapkw)?'internal search hard-coded,':'';if(wap_ga.campaign){if(wap_ga.qs.cid){wap_ga.config.campaign.cname=wap_ga.qs.cid;wap_ga.config.campaign.source=waGetPaidSource();wap_ga.config.campaign.medium='cpc';}
ga_payload.metric['9,hit']='1';ga_payload.dimension['27,hit']='load';ga_payload.dimension['28,hit']='load:page:std';}
else{ga_payload.metric['8,hit']='1';ga_payload.dimension['27,hit']='load';ga_payload.dimension['28,hit']='load:page:std';}
if(wap_ga.qs.cid||wap_ga.qs.gclid){if(wap_ga.qs.gclid){errorType="campaign.sem.google: ";error+=(wap_ga.qs.cid)?'':'no campaign id,';error+=(wap_ga.qs.utm)?'manual tagging with auto-tagging,':'';}
else{errorType="campaign.sem.other: ";error+=(wap_ga.qs.utm)?'':'no utm tagging,';}
error+=errorwapkw;}
if(wap_ga.qs.dfaid||wap_ga.qs.dclid){errorType="campaign.dcm: ";error+=(wap_ga.qs.dfaid)?'':'no dfaid,';error+=(wap_ga.qs.dclid)?'':'no auto-tagging,';error+=(wap_ga.qs.utm)?'manual tagging with auto-tagging,':'';error+=errorwapkw;}
if(error!=''){error=error.substr(0,error.length-1);ga_payload.dimension['66,page']=errorType+error;ga_payload.metric['57,hit']='1';}};wap_ga.config.tms_map=function(){for(var key in wap_ga.tms){if(wap_ga.tms.hasOwnProperty(key)){if(/dimension/.test(key)){var dimVal=key.split("dimension")[1]+",page";var gk=wap_ga.tms[key];if(/24|50|51|52|53|54|100|101|102|103|104|105/.test(key)){}
else{gk=gk.toLowerCase();}
ga_payload.dimension[dimVal]=gk;}
if(/metric/.test(key)){var dimVal=key.split("dimension")[1]+",hit";ga_payload.metric[dimVal]=wap_ga.tms[key];}
}}};var ga_customVars=(wap_ga.win.ga_customVars)?wap_ga.win.ga_customVars:{},ga_payload=(typeof ga_payload!=="undefined")?ga_payload:{"dimension":{},"metric":{}},ga_domain=setCookieDomainGA(),ua_account=setUaAccount(),ga_trackVideoJs="true",_gaq=_gaq||[];function setCookieDomainGA(){var cookieDomain=location.hostname;cookieDomain=cookieDomain.replace(/(.*)\.intel/,".intel");return cookieDomain;}function waSetCookieGA(b,c){var a=new Date();a.setTime(a.getTime()+(365*24*3600*1000));wap_ga.doc.cookie=b+"="+escape(c)+"; expires="+a.toGMTString()+"; path=/; domain="+ga_domain}function waNewIdGA(){var a="{";for(var b=1;b<=32;b++){var c=Math.floor(Math.random()*16).toString(16);a+=c;if((b==8)||(b==12)||(b==16)||(b==20)){a+="-"}}a+="}";return a};function waGetCookieGA(d){var b=d+"=";var f=b.length;var a=wap_ga.doc.cookie.length;var e=0;while(e<a){var c=e+f;if(wap_ga.doc.cookie.substring(e,c)==b){return waGetCookieValGA(c)}e=wap_ga.doc.cookie.indexOf(" ",e)+1;if(e==0){break}}return null};function waGetCookieValGA(b){var a=wap_ga.doc.cookie.indexOf(";",b);if(a==-1){a=wap_ga.doc.cookie.length}return unescape(wap_ga.doc.cookie.substring(b,a))};function setUaAccount(){var gaAccount,gaDevAccount;if(typeof wap_ga.win.ga_account!=="undefined"){gaAccount=wap_ga.win.ga_account;}
else{gaAccount='UA-35949610-1';}
if(wa_env){if(typeof wap_ga.win.ga_accountOverride!=="undefined"){gaAccount=wap_ga.win.ga_accountOverride;}}
if(typeof wap_ga.win.ga_dev_accounts!=="undefined"){gaDevAccount=wap_ga.win.ga_dev_accounts;}
else{var gaDevAccount='UA-41505236-1';}
var ga_accounts=(wa_env)?gaAccount:gaDevAccount;return ga_accounts;}
function trackGaPage(virtualPage,callback){ga_customVars.config('page');gawap(function(){virtualPage=(typeof virtualPage==="undefined")?location.pathname:virtualPage;virtualPage=(virtualPage=="")?location.pathname:virtualPage;virtualPage=(virtualPage.charAt(0)=='/')?virtualPage:'/'+virtualPage;var trackers=gawap.getAll();for(var i=0;i<trackers.length;++i){var tracker=trackers[i],trackerName=tracker.get('name');gawap(trackerName+'.set','page',virtualPage.toLowerCase());var fo={'metric12':'1','metric42':'1','contentGroup1':utag_data.content_audience,'contentGroup2':utag_data.content_sub_audience,'hitCallback':function(){if(typeof callback!=="undefined"){callback();}
if(wap_ga.scroll){trackGaEvent('Navigation','scroll','0%',null,true);}}};ga_customVars.payload(trackerName,fo);gawap(trackerName+'.send','pageview',fo);if(i==0){var uacd_28=(typeof fo.dimension28!=="undefined")?fo.dimension28:'';var pageTypeAsset=(/(:asset$)/.test(uacd_28))?true:false;if(pageTypeAsset){gawapGoal('aer','asset');}else{gawapGoal('aer','page');}}}});}
function trackGaEvent(category,action,opt_label,opt_value,opt_noninteraction,callback){ga_customVars.config('event');var origAction=action,origLabel=opt_label;action=action.toLowerCase();opt_label=(typeof opt_label=="undefined")?opt_label:opt_label.toLowerCase();gawap(function(){var trackers=gawap.getAll(),fo={'eventCategory':category,'eventAction':action,'eventLabel':opt_label,'eventValue':opt_value,'contentGroup1':utag_data.content_audience,'contentGroup2':utag_data.content_sub_audience,'hitCallback':function(){if(typeof callback!=="undefined"){callback();}}};eventMap=category+":"+action;eventMap=eventMap.replace(/\s/g,'').toLowerCase()+"";if(wa_component_name!==""){fo.dimension19=wa_component_name;}else{fo.dimension19='no-component';}
var isGoalPCI=(/page:(.*)|search:(.*)|navigation:(scroll|click:(m|f|h|left-nav|selectlanguage))(.*)|components:click:(breadcrumbnav|navigator|uheader|header|footer|signin|myintel|global-)(.*)|useraccountactivity:(login|registration:intel-account)(.*)|social:referral(.*)/g).test(eventMap)?false:true;if(isGoalPCI){fo.metric55=1;fo.metric53=1;}
var isGoalShop=(/(^\/buy\/)|(\/(ultrabook|2-in-1|tablets|all-in-one)\/shop-)|(^\/..\/..\/products\/)|(pocket\.intel\.com)/).test(opt_label)?true:false;if(isGoalShop){fo.metric56=1;fo.metric54=1;}
if(utag.loader.RC("utag_main").conv1=="1"){isGoalShop=false;}
ga_customVars.payload(trackerName,fo);var defaultTracking=false;switch(true){case(/(^components:click)/.test(eventMap)):fo.dimension27='click';fo.dimension28=action;fo.dimension29=action.split(': ')[1]+':'+opt_label;fo.metric30=1;break;case(/videos:video:/.test(eventMap)):fo.eventCategory='Videos';fo.dimension27='video';fo.eventLabel=origLabel;var dimArray=origLabel.split(':'),vid29='',vid64='';for(var i=0;i<dimArray.length;i++)
{dimArray[i]=dimArray[i].replace(/^\s*/,"").replace(/\s*$/,"");if(i==0){if(dimArray[i]!==wap_ga.undef){vid29=dimArray[i].toLowerCase();}}
if(i==2){if(dimArray[i]!==wap_ga.undef){vid29+=":"+dimArray[i];vid64=dimArray[i];}}
if(i==3){if(dimArray[i]!==wap_ga.undef){vid29=dimArray[0].toLowerCase();vid64='';}}}
fo.dimension29=vid29;fo.dimension64=vid64;switch(true){case(/play/.test(eventMap)):gawapGoal('aer','vidstart');fo.dimension28='video:start';fo.metric15=1;break;case(/50/.test(eventMap)):gawapGoal('aer','vidmid');fo.dimension28='video:50';fo.metric16=1;fo.metric53=1;break;case(/75/.test(eventMap)):fo.dimension28='video:75';fo.metric17=1;break;case(/90/.test(eventMap)):fo.dimension28='video:90';fo.metric18=1;break;case(/95/.test(eventMap)):fo.dimension28='video:95';fo.metric19=1;break;case(/100/.test(eventMap)):fo.dimension28='video:100';fo.metric20=1;break;case(/share/.test(eventMap)):fo.dimension27='social';fo.dimension28='social:share';fo.metric26=1;fo.metric29=1;fo.metric53=1;trackGAsocial('intel',action,opt_label);break;case(/fullscreen/.test(eventMap)):fo.metric30=1;fo.dimension28='video:fullscreen';break;default:defaultTracking=true;break;}
break;case(/^search:/.test(eventMap)):fo.eventLabel=fo.eventLabel.toLowerCase();switch(true){case(/search-box/.test(eventMap)):fo.dimension27='search';fo.dimension28='search:'+action.split(': ')[1];fo.dimension41=opt_label;fo.metric39=1;break;case(/:filter|:sitefilter/.test(eventMap)):fo.dimension27='search';fo.dimension28='search:'+action.replace(/\s/,'').replace(/\s/g,'-');fo.metric32=1;fo.metric39=1;break;case(/additional|related/.test(eventMap)):fo.dimension27='search';fo.dimension28='search:search-results:'+action.split(': ')[1].replace(/\s/g,'-');fo.metric39=1;break;case(/menu/.test(eventMap)):fo.dimension27='click';fo.dimension28='click:'+opt_label;fo.metric30=1;break;default:fo.dimension27='click';fo.dimension28='click:'+action.replace(/\s/,'').replace(/\s/g,'-');fo.metric30=1;break;}
break;case(/^offline:/.test(eventMap)):switch(true){case(/download/.test(eventMap)):fo.dimension27='download';fo.dimension28='download:'+action.split(': ')[1];fo.metric37=1;fo.metric53=1;break;case(/print/.test(eventMap)):fo.dimension27='print';fo.dimension28='print:page';fo.metric33=1;break;default:defaultTracking=true;break;}
break;case(/^download:/.test(eventMap)):var fileExt=(fo.eventAction.match(/\.(...|....)$/g)+"").toLowerCase();try{fileExt=fileExt.split(".");fileExt=fileExt[1];}catch(err){}
fo.eventCategory='Offline';fo.eventLabel=fo.eventAction;fo.eventAction='download: '+fileExt;fo.dimension27='download';fo.dimension28='download:'+fo.eventAction.split(': ')[1];fo.metric37=1;fo.metric53=1;break;case(/^shop:/.test(eventMap)):switch(true){case(/buynow/.test(eventMap)):fo.dimension27='thirdparty';fo.dimension28='thirdparty:buy';fo.metric6=1;fo.metric7=1;fo.metric54=1;break;case(/buythird-party/.test(eventMap)):fo.dimension27='thirdparty';fo.dimension28='thirdparty:shop';fo.metric5=1;fo.metric7=1;fo.metric54=1;break;case(/reset/.test(eventMap)):fo.dimension27='click';fo.dimension28='click:reset';break;case(/filter/.test(eventMap)):fo.dimension27='filter';fo.dimension28=opt_label;fo.metric32=1;break;case(/compare/.test(eventMap)):fo.dimension27='click';fo.dimension28='click:compare';fo.metric46=1;break;default:defaultTracking=true;break;}
break;case(/^useraccountactivity:/.test(eventMap)):switch(true){case(/registration:start/.test(eventMap)):fo.dimension27='registration';fo.dimension28='registration:start';fo.metric1=1;break;case(/registration:complete/.test(eventMap)):fo.dimension27='registration';fo.dimension28='registration:complete';fo.metric2=1;if(/opt-in:/.test(opt_label)){fo.metric3=1;}
break;case(/registration:intel/.test(eventMap)):fo.dimension27='registration';fo.dimension28='registration:start';fo.metric1=1;break;case(/login:intel/.test(eventMap)):fo.dimension27='login';fo.dimension28='login:intel';fo.metric35=1;fo.metric53=1;break;case(/login:social/.test(eventMap)):fo.dimension27='login';fo.dimension28='login:social';fo.metric35=1;fo.metric53=1;break;case(/updateprofile|savecontent/.test(eventMap)):fo.dimension27='save';fo.dimension28='save:'+action.split(': ')[1].replace(/\s/g,'-');fo.metric34=1;break;default:defaultTracking=true;break;}
break;case(/^chat:/.test(eventMap)):fo.dimension27='chat';fo.dimension28='chat:'+opt_label.split(':')[0];fo.metric36=1;fo.metric53=1;break;case(/^tools/.test(eventMap)):fo.dimension27='tool';fo.dimension28='tool:'+action.split('\-tool:')[0];fo.metric47=1;break;case(/^comment/.test(eventMap)):fo.dimension29=fo.eventAction;fo.eventCategory='Social';fo.eventAction='comment: '+fo.eventAction;fo.dimension27='social';fo.dimension28='social:comment';fo.metric22=1;fo.metric29=1;fo.metric53=1;break;case(/^share|^email/.test(eventMap)):fo.eventCategory='Social';fo.dimension29=fo.eventAction;fo.eventAction=(action=='mailto')?'share: email':'share: '+fo.eventAction;fo.dimension27='social';fo.dimension28='social:share';fo.metric26=1;fo.metric29=1;fo.metric53=1;break;case(/^like/.test(eventMap)):fo.eventCategory='Social';fo.dimension29=fo.eventAction;fo.eventAction='like: '+fo.eventAction;fo.dimension27='social';fo.dimension28='social:like';fo.metric23=1;fo.metric29=1;fo.metric53=1;break;case(/^rss/.test(eventMap)):fo.dimension27=fo.eventCategory.toLowerCase();fo.eventCategory='User Account Activity';fo.eventAction='rss: '+fo.eventAction;fo.dimension28='rss:'+opt_label;break;case(/^follow/.test(eventMap)):fo.eventCategory='Social';fo.dimension29=fo.eventAction;fo.eventAction='follow: '+fo.eventAction;fo.dimension27='social';fo.dimension28='social:follow';fo.metric25=1;fo.metric29=1;break;case(/^third-party/.test(eventMap)):fo.dimension27='thirdparty';fo.dimension28='thirdparty:std';fo.metric6=1;fo.metric54=1;break;case(/^social:/.test(eventMap)):switch(true){case(/referral/.test(eventMap)):fo.dimension27='social';fo.dimension28='social:referral';fo.metric21=1;fo.metric29=1;break;case(/rate:/.test(eventMap)):fo.dimension27='social';fo.dimension28='social:rate';fo.metric28=1;fo.metric29=1;if(!fo.dimension29){fo.dimension29=location.pathname.toLowerCase();}
break;}
break;case(/^navigation:/.test(eventMap)):fo.dimension27='nav';switch(true){case(/megamenu|menu/.test(eventMap)):fo.dimension28='nav:menu';fo.dimension29='nav:menu:'+opt_label;fo.metric43=1;fo.eventAction='click: menu';break;case(/footer/.test(eventMap)):fo.dimension28='nav:footer';fo.metric43=1;break;case(/header/.test(eventMap)):fo.dimension28='nav:header';fo.metric43=1;break;case(/selectlanguage/.test(eventMap)):fo.dimension28='nav:language';fo.dimension29='nav:language:'+wap_ga.wa_local;fo.metric43=1;break;case(/scroll/.test(eventMap)):fo.dimension27='scroll';fo.dimension28='scroll:'+opt_label.split('%')[0];switch(true){case(/^0/.test(opt_label)):fo.metric31=1;fo.dimension29='baseline';break;case(/^25/.test(opt_label)):fo.metric48=1;break;case(/^50/.test(opt_label)):fo.metric49=1;break;case(/^75/.test(opt_label)):fo.metric50=1;break;case(/^100/.test(opt_label)):fo.metric51=1;break;}
break;case(/filter/.test(eventMap)):fo.dimension28='nav:filter';fo.metric43=1;fo.metric32=1;break;case(/in-page/.test(eventMap)):fo.dimension28='nav:in-page';fo.dimension29='nav:in-page:'+opt_label.split(':')[0];fo.metric43=1;break;case(/left/.test(eventMap)):fo.dimension28='nav:leftnav';fo.metric43=1;break;default:fo.dimension28='nav:in-page';fo.dimension29='nav:in-page:'+opt_label.split(':')[0];fo.metric43=1;fo.eventAction='click: in-page';fo.eventLabel=action.split(': ')[1]+':'+opt_label;break;}
break;case(/non-interaction:/.test(eventMap)):fo.eventCategory='Page';switch(true){case(/error/.test(eventMap)):fo.eventAction='error';break;default:fo.eventAction='goal:'+action.split(': ')[1];fo.eventLabel=action;fo.dimension27='ni';fo.metric55=0;fo.metric53=0;fo.dimension28='ni:goals';break;}
break;default:defaultTracking=true;break;}
if(defaultTracking){fo.dimension27='click';fo.dimension28='click:std';fo.metric30=1;}
var perEvent=(utag.loader.RC("utag_main").per!=="1")?true:false;if(perEvent){if(typeof fo.metric53!=="undefined"){if(fo.metric53==1){if(wap_tms.floodlight.fireTags){configDFAfloodiFrame(wap_tms.floodlight.adId,wap_tms.floodlight.per.type,wap_tms.floodlight.per.category,'ses');}
if(wap_tms.kenshoo.fireTags){kenshoo_conv(wap_tms.kenshoo.per,'','','','');}
utag.loader.SC("utag_main",{"per":"1;exp-session"});}}}
var pirEvent=(utag.loader.RC("utag_main").pir!=="1")?true:false;if(pirEvent){if(typeof fo.metric54!=="undefined"){if(fo.metric54==1){if(wap_tms.floodlight.fireTags){configDFAfloodiFrame(wap_tms.floodlight.adId,wap_tms.floodlight.pir.type,wap_tms.floodlight.pir.category,'ses');}
if(wap_tms.kenshoo.fireTags){kenshoo_conv(wap_tms.kenshoo.pir,'','','','');}
utag.loader.SC("utag_main",{"pir":"1;exp-session"});}}}
gawapGoal('ier',isGoalPCI,opt_noninteraction);if(isGoalShop){if(!opt_noninteraction){gawap(function(){var trackers=gawap.getAll();for(var i=0;i<trackers.length;++i){var tracker=trackers[i],trackerName=tracker.get('name');gawap(trackerName+'.send','event',{'eventCategory':'Page','eventAction':'goal:intel shop','eventLabel':opt_label,'dimension27':'ni','dimension28':'ni:goals','contentGroup1':utag_data.content_audience,'contentGroup2':utag_data.content_sub_audience,'nonInteraction':true});}});}
utag.loader.SC("utag_main",{"conv1":"1;exp-session"});}
for(var i=0;i<trackers.length;++i){var tracker=trackers[i],trackerName=tracker.get('name');if(opt_noninteraction){fo.nonInteraction=true;}
else{fo.metric38=1;fo.metric42=1;}
gawap(trackerName+'.send','event',fo);}
if(fo.eventCategory=="Social"){if(/^email|^referral|^reply|^post|^rate|^intel-/.test(action)){category=category+': '+action;action='intel';}
trackGAsocial(action,category.toLowerCase(),opt_label);}});wa_component_name='';}
function trackGAsocial(network,socialAction,opt_target,opt_pagePath,callback){gawap(function(){var trackers=gawap.getAll();for(var i=0;i<trackers.length;++i){var tracker=trackers[i],trackerName=tracker.get('name');var fo={'socialNetwork':network,'socialAction':socialAction,'socialTarget':opt_target};if(typeof callback!=="undefined"){fo.hitCallback=function(){callback();}}
ga_customVars.payload(trackerName,fo);gawap(trackerName+'.send','social',fo);}});}
function trackGaSocial(){}
function gawapGoal(goalType,type,opt){var cookieVal=waGetCookieGA('gawap_g');var getGoal=(cookieVal)?cookieVal.split("x"):'',aerVal='',ierVal='',cookieTemplate;for(var i=0,length=getGoal.length;i<length;i++){var setGoal=getGoal[i];if(i==0){aerVal=getGoal[i];}
if(i==1){ierVal=getGoal[i];}}
if(goalType=='aer'){var currentTime=new Date().getTime(),timeSinceLastPage=0,ageInSeconds=0,assetPageNum=0,pageNum=0,vidEvent='none',expireGoal1=0,goalNotReached=true;if(aerVal){goalNotReached=(aerVal.split('e')[1].charAt(0)=="0")?true:false;if(goalNotReached){pageNum=aerVal.split('p')[1];pageNum=pageNum.split('a');assetPageNum=pageNum[1].split('t');currentTime=Number(assetPageNum[1]);pageNum=Number(pageNum[0]);assetPageNum=Number(assetPageNum[0]);var ageInSeconds=(new Date().getTime()-new Date(currentTime).getTime())/1000;}}
switch(type){case"asset":assetPageNum++;pageNum++;break;case"page":pageNum++;break;case"vidstart":vidEvent='start';break;case"vidmid":vidEvent='mid';break;}
var sendGoal=false;if(goalNotReached){if(pageNum>=2){if(ageInSeconds>60){sendGoal=true;}}
if(assetPageNum>=2){sendGoal=true;}
if(/^vid/.test(type)){sendGoal=true;}
if(sendGoal){expireGoal1=1;gawap(function(){var trackers=gawap.getAll();for(var i=0;i<trackers.length;++i){var tracker=trackers[i],trackerName=tracker.get('name');gawap(trackerName+'.send','event',{'eventCategory':'Page','eventAction':'goal:aer','eventLabel':'page='+pageNum+':asset='+assetPageNum+':vid='+vidEvent,'dimension27':'ni','dimension28':'ni:goals','dimension29':'page='+pageNum+':asset='+assetPageNum+':vid='+vidEvent,'metric52':'1','contentGroup1':utag_data.content_audience,'contentGroup2':utag_data.content_sub_audience,'nonInteraction':true});}});}
var addIER=(ierVal)?ierVal+'x':'';cookieTemplate="e"+expireGoal1+"p"+pageNum+"a"+assetPageNum+"t"+currentTime+"x"+addIER;document.cookie='gawap_g='+cookieTemplate+';path=/;domain='+ga_domain;}}
if(goalType=='ier'){var expireGoal2=0,nonInteractionNum,univeralNum,goalNotReached2=true;if(ierVal==""){goalNotReached2=true;nonInteractionNum=0;univeralNum=0;}
else{goalNotReached2=(ierVal.split('e')[1].charAt(0)=="0")?true:false;univeralNum=ierVal.split('u')[1];univeralNum=univeralNum.split('ni');nonInteractionNum=Number(univeralNum[1].split('x'));univeralNum=Number(univeralNum[0]);}
if(goalNotReached2){if(type){expireGoal2=1;gawap(function(){var trackers=gawap.getAll();for(var i=0;i<trackers.length;++i){var tracker=trackers[i],trackerName=tracker.get('name');gawap(trackerName+'.send','event',{'eventCategory':'Page','eventAction':'goal:ier','eventLabel':'universal='+univeralNum+':non-interaction='+nonInteractionNum,'dimension27':'ni','dimension28':'ni:goals','dimension29':'universal='+univeralNum+':non-interaction='+nonInteractionNum,'contentGroup1':utag_data.content_audience,'contentGroup2':utag_data.content_sub_audience,'nonInteraction':true});}});}
else{if(opt){nonInteractionNum++;}
else{univeralNum++;}}
cookieTemplate=aerVal+"x"+"e"+expireGoal2+"u"+univeralNum+"ni"+nonInteractionNum+"x";document.cookie='gawap_g='+cookieTemplate+';path=/;domain='+ga_domain;}}}
function gaBrightCoveTracking(trackType,gaEventCategory,gaEventAction,gaEventLabel){ga_payload.dimension['29,hit']="brightcove:"+gaEventLabel.split(':')[2];switch(gaEventAction){case"video: share: link":case"video: share: embed":case"video: share: blog":case"video: share: email":trackGaEvent(gaEventCategory,gaEventAction,gaEventLabel);break;case"video: play":trackGaEvent(gaEventCategory,gaEventAction,gaEventLabel);break;case"video: 50% complete":trackGaEvent(gaEventCategory,gaEventAction,gaEventLabel);break;case"video: 100% complete":trackGaEvent(gaEventCategory,gaEventAction,gaEventLabel);break;case"video: 75% complete":case"video: 90% complete":case"video: 95% complete":case"video: fullscreen":trackGaEvent(gaEventCategory,gaEventAction,gaEventLabel);break;}}
function configGA(accountID,trackerId){gawap('create',accountID,{'name':'waptracker'+trackerId,'cookieDomain':'auto','siteSpeedSampleRate':wap_ga.sitespeed,'cookieName':'gawap'});wap_ga.config.campaign();wap_ga.config.tms_map();gawap(function(){var trackers=gawap.getAll();var pageTitle=utag_data['content_audience']+":"+utag_data['content_sub_audience']+":"+utag_data['content_program']+":"+utag_data['content_org_initiative']+":"+utag_data['content_sub_org_initiative']+":"+utag_data['content_product']+":"+utag_data.wa_site_id+' - '+wap_ga.doc.title;for(var i=0;i<trackers.length;++i){var tracker=trackers[i],trackerName=tracker.get('name'),clientId=tracker.get('clientId');ga_payload.dimension['101,page']=clientId;gawap(trackerName+'.require','displayfeatures');if(wap_ga.tms.enhancedLinkAttribution=="true"){gawap(trackerName+'.require','linkid',{'cookieName':'_ela','duration':45,'levels':8});}
gawap(trackerName+'.set','anonymizeIp',true);if(wap_ga.campaign){gawap(trackerName+'.set','campaignName',wap_ga.config.campaign.cname);gawap(trackerName+'.set','campaignSource',wap_ga.config.campaign.source);gawap(trackerName+'.set','campaignMedium',wap_ga.config.campaign.medium);}
if(wap_tms.referrer!==''){gawap(trackerName+'.set','dimension110',wap_tms.referrer);gawap(trackerName+'.set','contentGroup3',wap_tms.referrer);}
gawap(trackerName+'.set','title',pageTitle);}});}
function waGetPaidSource(){var campaignSourceDomain=(wap_ga.doc.referrer!=="")?wap_ga.doc.referrer.split('/')[2].toLowerCase():"unknown";switch(true){case/google/.test(campaignSourceDomain):campaignSource="google";break;case/yahoo/.test(campaignSourceDomain):campaignSource="yahoo";break;case/bing/.test(campaignSourceDomain):campaignSource="bing";break;case/daum/.test(campaignSourceDomain):campaignSource="daum";break;case/baidu/.test(campaignSourceDomain):campaignSource="baidu";break;case/eniro/.test(campaignSourceDomain):campaignSource="eniro";break;case/naver/.test(campaignSourceDomain):campaignSource="naver";break;case/pchome/.test(campaignSourceDomain):campaignSource="pchome";break;case/msn/.test(campaignSourceDomain):campaignSource="msn";break;case/aol/.test(campaignSourceDomain):campaignSource="aol";break;case/lycos/.test(campaignSourceDomain):campaignSource="lycos";break;case/ask/.test(campaignSourceDomain):campaignSource="ask";break;case/netscape/.test(campaignSourceDomain):campaignSource="netscape";break;case/mamma/.test(campaignSourceDomain):campaignSource="mamma";break;case/about/.test(campaignSourceDomain):campaignSource="about";break;case/voila/.test(campaignSourceDomain):campaignSource="voila";break;case/virgilio/.test(campaignSourceDomain):campaignSource="virgilio";break;case/live/.test(campaignSourceDomain):campaignSource="live";break;case/alice/.test(campaignSourceDomain):campaignSource="alice";break;case/yandex/.test(campaignSourceDomain):campaignSource="yandex";break;case/najdi/.test(campaignSourceDomain):campaignSource="najdi";break;case/seznam/.test(campaignSourceDomain):campaignSource="seznam";break;case/rakuten/.test(campaignSourceDomain):campaignSource="rakuten";break;case/biglobe/.test(campaignSourceDomain):campaignSource="biglobe";break;case/onet/.test(campaignSourceDomain):campaignSource="onet";break;case/wp/.test(campaignSourceDomain):campaignSource="wp";break;case/yam/.test(campaignSourceDomain):campaignSource="yam";break;case/kvasir/.test(campaignSourceDomain):campaignSource="kvasir";break;case/ozu/.test(campaignSourceDomain):campaignSource="ozu";break;case/terra/.test(campaignSourceDomain):campaignSource="terra";break;case/rambler/.test(campaignSourceDomain):campaignSource="rambler";break;case/conduit/.test(campaignSourceDomain):campaignSource="conduit";break;case/babylon/.test(campaignSourceDomain):campaignSource="babylon";break;case/search-results/.test(campaignSourceDomain):campaignSource="search-results";break;case/comcast/.test(campaignSourceDomain):campaignSource="comcast";break;case/incredimail/.test(campaignSourceDomain):campaignSource="incredimail";break;case/go.mail.ru/.test(campaignSourceDomain):campaignSource="go.mail.ru";break;case/search.centrum.cz/.test(campaignSourceDomain):campaignSource="search.centrum.cz";break;case/startsiden/.test(campaignSourceDomain):campaignSource="startsiden";break;default:campaignSource=campaignSourceDomain.replace(/^www\./,'');}
return campaignSource;}
var gaLoadUrl='//www.google-analytics.com/analytics.js';if(utag_data.wa_geo=='prc'){gaLoadUrl=('https:'==document.location.protocol)?'https://www-ssl.intel.com/content/dam/www/global/wap/analytics.js':'http://www.intel.cn/content/dam/www/global/wap/analytics.js';}
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script',gaLoadUrl,wap_ga.name);var uaga_id=ua_account.split(',');for(var i=0;i<uaga_id.length;i++){configGA(uaga_id[i],i);}
ga_customVars.config=function(hitType){if(hitType=='page'){ga_payload.dimension['55,page']=wap_ga.section+":"+wap_ga.pagegroup.toLowerCase();ga_payload.dimension['56,page']=decodeURIComponent(location.search);ga_payload.dimension['56,page']=ga_payload.dimension['56,page'].replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/i,'removed@email');ga_payload.dimension['57,page']=navigator.userAgent.toLowerCase();ga_payload.dimension['61,page']=wap_ga.code;if(wap_ga.qs.wapkw){ga_payload.dimension['42,page']=wap_ga.qs.wapkw.toLowerCase();ga_payload.metric['40,hit']='1';}}
},ga_customVars.payload=function(trackerName,fo){for(var key in ga_payload){var obj=ga_payload[key];for(var prop in obj){var slot=prop.split(',');var keySlot=key+slot[0];if(obj[prop]!==''){if(key=="metric"){if(slot[1]=='hit'){if(obj[prop]!=0){fo[keySlot]=Number(obj[prop]);ga_payload.metric[slot]=0;}}
else{gawap(trackerName+'.set',keySlot,Number(obj[prop]));}}
else{if(slot[1]=='hit'){fo[keySlot]=obj[prop]+"";ga_payload.dimension[slot]='';}
else{gawap(trackerName+'.set',keySlot,obj[prop]+"");}}}}}
return fo;};if(wap_ga.autofire){trackGaPage(wap_ga.pagename,wap_ga.callback);}
if(wap_ga.scroll){if(window.jQuery){if(window.$){docHeight=$(document).height();$(document).ready(function(){(function($,window,document,undefined){"use strict";var defaults={minHeight:0,elements:[],percentage:true,userTiming:false,pixelDepth:true};var $window=$(window),cache=[],lastPixelDepth=0;$.scrollDepth=function(options){var startTime=+new Date;options=$.extend({},defaults,options);if($(document).height()<options.minHeight){return;}
function sendEvent(action,label,scrollDistance,timing){if(options.pixelDepth&&arguments.length>2&&scrollDistance>lastPixelDepth){lastPixelDepth=scrollDistance;ga_payload.dimension['29,hit']=rounded(scrollDistance);trackGaEvent('Navigation','scroll',label,null,true);}
}
function calculateMarks(docHeight){return{'25%':parseInt(docHeight*0.25,10),'50%':parseInt(docHeight*0.50,10),'75%':parseInt(docHeight*0.75,10),'100%':docHeight-5};}
function checkMarks(marks,scrollDistance,timing){$.each(marks,function(key,val){if($.inArray(key,cache)===-1&&scrollDistance>=val){sendEvent('Percentage',key,scrollDistance,timing);cache.push(key);}});}
function checkElements(elements,scrollDistance,timing){$.each(elements,function(index,elem){if($.inArray(elem,cache)===-1&&$(elem).length){if(scrollDistance>=$(elem).offset().top){sendEvent('Elements',elem,scrollDistance,timing);cache.push(elem);}}});}
function rounded(scrollDistance){return(Math.floor(scrollDistance/250)*250).toString();}
function throttle(func,wait){var context,args,result;var timeout=null;var previous=0;var later=function(){previous=new Date;timeout=null;result=func.apply(context,args);};return function(){var now=new Date;if(!previous)previous=now;var remaining=wait-(now-previous);context=this;args=arguments;if(remaining<=0){clearTimeout(timeout);timeout=null;previous=now;result=func.apply(context,args);}else if(!timeout){timeout=setTimeout(later,remaining);}
return result;};}
$window.on('scroll.scrollDepth',throttle(function(){var docHeight=$(document).height(),winHeight=window.innerHeight?window.innerHeight:$window.height(),scrollDistance=$window.scrollTop()+winHeight,marks=calculateMarks(docHeight),timing=+new Date-startTime;if(cache.length>=4+options.elements.length){$window.off('scroll.scrollDepth');return;}
if(options.elements){checkElements(options.elements,scrollDistance,timing);}
if(options.percentage){checkMarks(marks,scrollDistance,timing);}},500));};})(jQuery,window,document);$(document).ready(function(){$.scrollDepth();});});}}}
(function(){var e=window,h=document,k="replace";var s=function(a,c){var d=void 0;if("function"==typeof a.get&&"function"==typeof a.set){var b=c||{},g=b.hasOwnProperty("cookieName")?b.cookieName:"_gali",q=b.hasOwnProperty("cookieTimeout")?b.cookieTimeout:30,r=b.hasOwnProperty("levels")?b.levels:3,b=a.get("cookieDomain"),l=a.get("cookiePath"),f=new n(g,b,q,l);d||(d=f.get());d&&a.set("&linkid",d);p(function(a){a=a||e.event;a=a.target||a.srcElement;for(var b,c=0;a&&c<=r;c++){if(b=a.getAttribute("id")){a=b;100<a.length?f.remove():a?f.set(a):f.remove();return}a=a.parentElement}f.remove()})}};var t=function(a,c,d,b,g){c=encodeURIComponent(c)[k](/\(/g,"%28")[k](/\)/g,"%29");a=a+"="+c+"; path="+(d||"/")+"; ";g&&(a+="expires="+(new Date((new Date).getTime()+g)).toGMTString()+"; ");b&&"none"!=b&&(a+="domain="+b+";");b=h.cookie;h.cookie=a;return b!=h.cookie},p=function(a){var c=h.body;try{c.addEventListener?c.addEventListener("click",a,!1):c.attachEvent&&c.attachEvent("onclick",a)}catch(d){}};var n=function(a,c,d,b){this.get=function(){for(var b=void 0,c=[],d=h.cookie.split(";"),l=new RegExp("^\\s*"+a+"=\\s*(.*?)\\s*$"),f=0;f<d.length;f++){var m=d[f].match(l);m&&c.push(decodeURIComponent(m[1][k](/%28/g,"(")[k](/%29/g,")")))}for(d=0;d<c.length;d++)c[d]&&(b=c[d]);return b};this.set=function(g){return t(a,g,b,c,1E3*d)};this.remove=function(){return t(a,"",b,c,-100)}};(function(){e.gaplugins=e.gaplugins||{};e.gaplugins.LinkId=s;var a=e.GoogleAnalyticsObject||"ga";e[a]=e[a]||function(){(e[a].q=e[a].q||[]).push(arguments)};e[a]("provide","linkid",s)})();})();wap_tms.ga_loaded=true;