#
# Makefile for APEX loader
#
#   Copyright (C) 2004 Marc Singer
#   with modifications by David Anders
#
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   version 2 as published by the Free Software Foundation.
#   Please refer to the file debian/copyright for further details.
#

obj-y := serial.o env.o

obj-$(CONFIG_MACH_M7200)     += init-m7200.o timer-s3c2410.o
